# Generated by Django 5.2.17 on 2026-09-19 05:48

import content.seo
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Startseite'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='accessible_video_label',
            field=models.CharField(blank=True, max_length=240, verbose_name='Barrierefreie Video-Beschreibung'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='candidate_cta',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Optional. Muss eine vollständige HTTPS-URL sein.', max_length=300, validators=[content.seo.validate_https_absolute_url], verbose_name='Kanonische URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='employer_cta',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='follow_on_sections',
            field=wagtail.fields.StreamField([('section', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift', 'max_length': 240, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1), ('image', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_chapters',
            field=wagtail.fields.StreamField([('chapter', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 160, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift', 'max_length': 240}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 3), ('is_external', 4), ('page', 5), ('external_url', 6)]], {'label': 'CTA', 'required': False}), 8: ('wagtail.blocks.IntegerBlock', (), {'label': 'Startsekunde', 'min_value': 0, 'required': False}), 9: ('wagtail.blocks.IntegerBlock', (), {'label': 'Endsekunde', 'min_value': 0, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('paragraph', 2), ('cta', 7), ('start_seconds', 8), ('end_seconds', 9)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Intro-Poster'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Intro-Video'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='last_reviewed',
            field=models.DateField(blank=True, help_text='Für rechtliche Seiten das Datum der letzten inhaltlichen Prüfung.', null=True, verbose_name='Zuletzt geprüft am'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='navigation_label',
            field=models.CharField(blank=True, help_text='Optionaler kurzer Name für Navigation und Breadcrumbs.', max_length=120, verbose_name='Navigationsbezeichnung'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='noindex',
            field=models.BooleanField(default=False, verbose_name='Nicht indexieren'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Open-Graph-Beschreibung'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Open-Graph-Bild'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Open-Graph-Titel'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='scroll_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Scroll-Hero-Poster'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='scroll_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Scroll-Hero-Video'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tap_to_play_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tap-to-play-Label'),
        ),
    ]
