# Generated by Django 5.2.17 on 2026-09-19 05:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='candidate_cta',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='employer_cta',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_chapters',
            field=wagtail.fields.StreamField([('chapter', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 160, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift', 'max_length': 240}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 3), ('is_external', 4), ('page', 5), ('external_url', 6)]], {'label': 'CTA', 'required': False}), 8: ('wagtail.blocks.IntegerBlock', (), {'label': 'Startsekunde', 'min_value': 0, 'required': False}), 9: ('wagtail.blocks.IntegerBlock', (), {'label': 'Endsekunde', 'min_value': 0, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('paragraph', 2), ('cta', 7), ('start_seconds', 8), ('end_seconds', 9)]], {})}),
        ),
    ]
