# Generated by Django 5.2.17 on 2026-09-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_candidate_cta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_video_url',
            field=models.URLField(blank=True, verbose_name='Intro-Video-URL (Cloudinary)'),
        ),
    ]
