# Generated by Django 5.2.17 on 2026-09-19 05:42

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='KP Personalberatung', max_length=160, verbose_name='Website-Name')),
                ('primary_navigation', wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Externer Link', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('footer_navigation', wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Externer Link', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('legal_navigation', wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Externer Link', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('social_links', wagtail.fields.StreamField([('item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 80}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1)]], {})})),
                ('default_telephone', models.CharField(blank=True, max_length=80, verbose_name='Standard-Telefon')),
                ('default_email', models.EmailField(blank=True, max_length=254, verbose_name='Standard-E-Mail')),
                ('offices', wagtail.fields.StreamField([('office', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Straße', 'max_length': 160}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Postleitzahl', 'max_length': 20}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Stadt', 'max_length': 120}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Telefon', 'max_length': 80, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'E-Mail', 'max_length': 254, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Karten-URL', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 0), ('street', 1), ('postal_code', 2), ('city', 3), ('telephone', 4), ('email', 5), ('map_url', 6)]], {})})),
                ('footer_company_text', models.TextField(blank=True, verbose_name='Unternehmenstext im Footer')),
                ('copyright_text', models.CharField(blank=True, max_length=240, verbose_name='Copyright-Text')),
                ('employer_cta_label', models.CharField(blank=True, max_length=120, verbose_name='CTA Arbeitgeber')),
                ('candidate_cta_label', models.CharField(blank=True, max_length=120, verbose_name='CTA Kandidaten')),
                ('calendly_url', models.URLField(blank=True, verbose_name='Calendly-URL')),
                ('cookie_heading', models.CharField(blank=True, max_length=160, verbose_name='Cookie-Banner Überschrift')),
                ('cookie_explanation', models.TextField(blank=True, verbose_name='Cookie-Banner Erklärung')),
                ('cookie_accept_label', models.CharField(blank=True, max_length=80, verbose_name='Cookie: Akzeptieren')),
                ('cookie_reject_label', models.CharField(blank=True, max_length=80, verbose_name='Cookie: Ablehnen')),
                ('cookie_customize_label', models.CharField(blank=True, max_length=80, verbose_name='Cookie: Anpassen')),
                ('cookie_privacy_link_label', models.CharField(blank=True, max_length=120, verbose_name='Cookie: Datenschutz-Link')),
                ('analytics_enabled', models.BooleanField(default=False, verbose_name='Analytics aktiviert')),
                ('organization_legal_name', models.CharField(blank=True, max_length=200, verbose_name='Organisation: Rechtsname')),
                ('organization_address', models.CharField(blank=True, max_length=300, verbose_name='Organisation: Adresse')),
                ('organization_telephone', models.CharField(blank=True, max_length=80, verbose_name='Organisation: Telefon')),
                ('organization_email', models.EmailField(blank=True, max_length=254, verbose_name='Organisation: E-Mail')),
                ('organization_social_profiles', wagtail.fields.StreamField([('profile', 0)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Social-Profil'})})),
                ('compact_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo (kompakt)')),
                ('cookie_privacy_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Datenschutzseite')),
                ('default_social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Standard-Social-Bild')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon')),
                ('full_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo (vollständig)')),
                ('mobile_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo (mobil)')),
                ('organization_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Organisation: Logo')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'KP Website-Einstellungen',
            },
        ),
    ]
