# Generated by Django 5.2.17 on 2026-09-19 05:46

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=120, unique=True, verbose_name='Quellschlüssel')),
                ('quote', models.TextField(verbose_name='Zitat')),
                ('person_label', models.CharField(blank=True, max_length=160, verbose_name='Personenbezeichnung')),
                ('role', models.CharField(blank=True, max_length=160, verbose_name='Rolle')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Organisation')),
                ('audience', models.CharField(choices=[('employer', 'Arbeitgeber'), ('candidate', 'Kandidat')], max_length=20, verbose_name='Zielgruppe')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Anzeigereihenfolge')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Referenzstimme',
                'verbose_name_plural': 'Referenzstimmen',
                'ordering': ['display_order', 'source_key'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=120, unique=True, verbose_name='Quellschlüssel')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('short_description', models.TextField(blank=True, verbose_name='Kurzbeschreibung')),
                ('icon_identifier', models.CharField(choices=[('briefcase', 'Aktenkoffer'), ('chart', 'Diagramm'), ('globe', 'Globus'), ('people', 'Personen'), ('document', 'Dokument'), ('search', 'Suche')], max_length=40, verbose_name='Icon')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Anzeigereihenfolge')),
                ('audience', models.CharField(choices=[('employer', 'Arbeitgeber'), ('candidate', 'Kandidat'), ('both', 'Beide')], max_length=20, verbose_name='Zielgruppe')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('detail_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Detailseite')),
            ],
            options={
                'verbose_name': 'Leistung',
                'verbose_name_plural': 'Leistungen',
                'ordering': ['display_order', 'source_key'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=120, unique=True, verbose_name='Quellschlüssel')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('role', models.CharField(blank=True, max_length=160, verbose_name='Rolle')),
                ('biography', wagtail.fields.RichTextField(blank=True, verbose_name='Biografie')),
                ('expertise_tags', wagtail.fields.StreamField([('tag', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Expertise', 'max_length': 80})}, verbose_name='Expertise-Tags')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('telephone', models.CharField(blank=True, max_length=80, verbose_name='Telefon')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn-URL')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Porträt')),
            ],
            options={
                'verbose_name': 'Teammitglied',
                'verbose_name_plural': 'Teammitglieder',
                'ordering': ['name', 'source_key'],
            },
        ),
    ]
