# Generated by Django 5.2.17 on 2026-09-19 05:48

import content.seo
import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_testimonial_service_teammember'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('og_title', models.CharField(blank=True, max_length=60, verbose_name='Open-Graph-Titel')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='Open-Graph-Beschreibung')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Muss eine vollständige HTTPS-URL sein.', max_length=300, validators=[content.seo.validate_https_absolute_url], verbose_name='Kanonische URL')),
                ('noindex', models.BooleanField(default=False, verbose_name='Nicht indexieren')),
                ('navigation_label', models.CharField(blank=True, help_text='Optionaler kurzer Name für Navigation und Breadcrumbs.', max_length=120, verbose_name='Navigationsbezeichnung')),
                ('last_reviewed', models.DateField(blank=True, help_text='Für rechtliche Seiten das Datum der letzten inhaltlichen Prüfung.', null=True, verbose_name='Zuletzt geprüft am')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=160, verbose_name='Hero-Eyebrow')),
                ('hero_heading', models.CharField(max_length=240, verbose_name='Hero-Überschrift')),
                ('hero_text', wagtail.fields.RichTextField(blank=True, verbose_name='Hero-Text')),
                ('hero_ctas', wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('who_we_are_heading', models.CharField(blank=True, max_length=240, verbose_name='Wer-wir-sind-Überschrift')),
                ('who_we_are_sections', wagtail.fields.StreamField([('section', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift', 'max_length': 240, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1), ('image', 2)]], {})})),
                ('statistics', wagtail.fields.StreamField([('stat', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Wert', 'max_length': 80}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 160}), 2: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 1)]], {})})),
                ('team_members', wagtail.fields.StreamField([('member', 1)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('content.TeamMember',), {'label': 'Teammitglied'}), 1: ('wagtail.blocks.StructBlock', [[('team_member', 0)]], {})})),
                ('values', wagtail.fields.StreamField([('value', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift', 'max_length': 160}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 1)]], {})})),
                ('contact_cta', wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('hero_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero-Hintergrundbild')),
                ('hero_background_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Hero-Hintergrundvideo')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Open-Graph-Bild')),
            ],
            options={
                'verbose_name': 'Über-uns-Seite',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='CandidatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('og_title', models.CharField(blank=True, max_length=60, verbose_name='Open-Graph-Titel')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='Open-Graph-Beschreibung')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Muss eine vollständige HTTPS-URL sein.', max_length=300, validators=[content.seo.validate_https_absolute_url], verbose_name='Kanonische URL')),
                ('noindex', models.BooleanField(default=False, verbose_name='Nicht indexieren')),
                ('navigation_label', models.CharField(blank=True, help_text='Optionaler kurzer Name für Navigation und Breadcrumbs.', max_length=120, verbose_name='Navigationsbezeichnung')),
                ('last_reviewed', models.DateField(blank=True, help_text='Für rechtliche Seiten das Datum der letzten inhaltlichen Prüfung.', null=True, verbose_name='Zuletzt geprüft am')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=160, verbose_name='Hero-Eyebrow')),
                ('hero_heading', models.CharField(max_length=240, verbose_name='Hero-Überschrift')),
                ('hero_text', wagtail.fields.RichTextField(blank=True, verbose_name='Hero-Text')),
                ('hero_ctas', wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('services', wagtail.fields.StreamField([('service', 1)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('content.Service',), {'label': 'Leistung'}), 1: ('wagtail.blocks.StructBlock', [[('service', 0)]], {})})),
                ('testimonials', wagtail.fields.StreamField([('testimonial', 1)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('content.Testimonial',), {'label': 'Referenzstimme'}), 1: ('wagtail.blocks.StructBlock', [[('testimonial', 0)]], {})})),
                ('closing_cta', wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('contact_details', wagtail.fields.RichTextField(blank=True, verbose_name='Kontaktangaben')),
                ('hero_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero-Hintergrundbild')),
                ('hero_background_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Hero-Hintergrundvideo')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Open-Graph-Bild')),
            ],
            options={
                'verbose_name': 'Kandidatenseite',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='EmployerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('og_title', models.CharField(blank=True, max_length=60, verbose_name='Open-Graph-Titel')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='Open-Graph-Beschreibung')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Muss eine vollständige HTTPS-URL sein.', max_length=300, validators=[content.seo.validate_https_absolute_url], verbose_name='Kanonische URL')),
                ('noindex', models.BooleanField(default=False, verbose_name='Nicht indexieren')),
                ('navigation_label', models.CharField(blank=True, help_text='Optionaler kurzer Name für Navigation und Breadcrumbs.', max_length=120, verbose_name='Navigationsbezeichnung')),
                ('last_reviewed', models.DateField(blank=True, help_text='Für rechtliche Seiten das Datum der letzten inhaltlichen Prüfung.', null=True, verbose_name='Zuletzt geprüft am')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=160, verbose_name='Hero-Eyebrow')),
                ('hero_heading', models.CharField(max_length=240, verbose_name='Hero-Überschrift')),
                ('hero_text', wagtail.fields.RichTextField(blank=True, verbose_name='Hero-Text')),
                ('hero_ctas', wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('intro_heading', models.CharField(blank=True, max_length=240, verbose_name='Intro-Überschrift')),
                ('intro_body', wagtail.fields.RichTextField(blank=True, verbose_name='Intro-Text')),
                ('services', wagtail.fields.StreamField([('service', 1)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('content.Service',), {'label': 'Leistung'}), 1: ('wagtail.blocks.StructBlock', [[('service', 0)]], {})})),
                ('why_kastell', wagtail.fields.StreamField([('section', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift', 'max_length': 240, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1), ('image', 2)]], {})})),
                ('statistics', wagtail.fields.StreamField([('stat', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Wert', 'max_length': 80}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 160}), 2: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 1)]], {})})),
                ('testimonials', wagtail.fields.StreamField([('testimonial', 1)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('content.Testimonial',), {'label': 'Referenzstimme'}), 1: ('wagtail.blocks.StructBlock', [[('testimonial', 0)]], {})})),
                ('recruitment_region_heading', models.CharField(blank=True, max_length=240, verbose_name='Regionen-Überschrift')),
                ('recruitment_region_copy', wagtail.fields.RichTextField(blank=True, verbose_name='Regionen-Text')),
                ('recruitment_regions', wagtail.fields.StreamField([('region', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Region', 'max_length': 120})})),
                ('closing_cta', wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('calendly_cta_label', models.CharField(blank=True, max_length=120, verbose_name='Calendly-CTA')),
                ('hero_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero-Hintergrundbild')),
                ('hero_background_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Hero-Hintergrundvideo')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Open-Graph-Bild')),
            ],
            options={
                'verbose_name': 'Arbeitgeberseite',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
