# Generated by Django 5.2.17 on 2026-09-19 05:50

import content.seo
import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_aboutpage_candidatepage_employerpage'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('og_title', models.CharField(blank=True, max_length=60, verbose_name='Open-Graph-Titel')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='Open-Graph-Beschreibung')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Muss eine vollständige HTTPS-URL sein.', max_length=300, validators=[content.seo.validate_https_absolute_url], verbose_name='Kanonische URL')),
                ('noindex', models.BooleanField(default=False, verbose_name='Nicht indexieren')),
                ('navigation_label', models.CharField(blank=True, help_text='Optionaler kurzer Name für Navigation und Breadcrumbs.', max_length=120, verbose_name='Navigationsbezeichnung')),
                ('last_reviewed', models.DateField(blank=True, help_text='Für rechtliche Seiten das Datum der letzten inhaltlichen Prüfung.', null=True, verbose_name='Zuletzt geprüft am')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=160, verbose_name='Hero-Eyebrow')),
                ('hero_heading', models.CharField(max_length=240, verbose_name='Hero-Überschrift')),
                ('hero_text', wagtail.fields.RichTextField(blank=True, verbose_name='Hero-Text')),
                ('hero_ctas', wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('page_heading', models.CharField(max_length=240, verbose_name='Seitenüberschrift')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Einleitung')),
                ('office_labels', wagtail.fields.StreamField([('office', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Büro-Bezeichnung', 'max_length': 120})}, help_text='Geordnete Bezeichnungen aus den Büros in KPSettings.')),
                ('website_url_label', models.CharField(blank=True, max_length=120, verbose_name='Website-URL-Bezeichnung')),
                ('website_url', models.URLField(blank=True, verbose_name='Website-URL')),
                ('closing_copy', wagtail.fields.RichTextField(blank=True, verbose_name='Abschlusstext')),
                ('hero_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero-Hintergrundbild')),
                ('hero_background_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Hero-Hintergrundvideo')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Open-Graph-Bild')),
            ],
            options={
                'verbose_name': 'Kontaktseite',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='CVPackagesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('og_title', models.CharField(blank=True, max_length=60, verbose_name='Open-Graph-Titel')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='Open-Graph-Beschreibung')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Muss eine vollständige HTTPS-URL sein.', max_length=300, validators=[content.seo.validate_https_absolute_url], verbose_name='Kanonische URL')),
                ('noindex', models.BooleanField(default=False, verbose_name='Nicht indexieren')),
                ('navigation_label', models.CharField(blank=True, help_text='Optionaler kurzer Name für Navigation und Breadcrumbs.', max_length=120, verbose_name='Navigationsbezeichnung')),
                ('last_reviewed', models.DateField(blank=True, help_text='Für rechtliche Seiten das Datum der letzten inhaltlichen Prüfung.', null=True, verbose_name='Zuletzt geprüft am')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=160, verbose_name='Hero-Eyebrow')),
                ('hero_heading', models.CharField(max_length=240, verbose_name='Hero-Überschrift')),
                ('hero_text', wagtail.fields.RichTextField(blank=True, verbose_name='Hero-Text')),
                ('hero_ctas', wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Intro')),
                ('packages', wagtail.fields.StreamField([('package', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Paketname', 'max_length': 160}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Preis (Anzeige)', 'max_length': 120}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Erfahrungsbereich', 'max_length': 160, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Zielgruppe', 'max_length': 160, 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Beschreibung', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 7: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('label', 5), ('is_external', 6), ('page', 7), ('external_url', 8)]], {'label': 'CTA', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('name', 0), ('price_display', 1), ('experience_range', 2), ('audience', 3), ('description', 4), ('cta', 9)]], {})})),
                ('how_it_works_heading', models.CharField(blank=True, max_length=240, verbose_name='So funktioniert es: Überschrift')),
                ('how_it_works_intro', wagtail.fields.RichTextField(blank=True, verbose_name='So funktioniert es: Intro')),
                ('how_it_works_steps', wagtail.fields.StreamField([('step', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift', 'max_length': 160}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 1)]], {})})),
                ('delivery_time_text', models.CharField(blank=True, max_length=240, verbose_name='Lieferzeit')),
                ('hero_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero-Hintergrundbild')),
                ('hero_background_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Hero-Hintergrundvideo')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Open-Graph-Bild')),
            ],
            options={
                'verbose_name': 'Bewerbungsunterlagen-Seite',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('og_title', models.CharField(blank=True, max_length=60, verbose_name='Open-Graph-Titel')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='Open-Graph-Beschreibung')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Muss eine vollständige HTTPS-URL sein.', max_length=300, validators=[content.seo.validate_https_absolute_url], verbose_name='Kanonische URL')),
                ('noindex', models.BooleanField(default=False, verbose_name='Nicht indexieren')),
                ('navigation_label', models.CharField(blank=True, help_text='Optionaler kurzer Name für Navigation und Breadcrumbs.', max_length=120, verbose_name='Navigationsbezeichnung')),
                ('last_reviewed', models.DateField(blank=True, help_text='Für rechtliche Seiten das Datum der letzten inhaltlichen Prüfung.', null=True, verbose_name='Zuletzt geprüft am')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Einleitung')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Rechtlicher Inhalt')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Open-Graph-Bild')),
            ],
            options={
                'verbose_name': 'Rechtliche Seite',
                'verbose_name_plural': 'Rechtliche Seiten',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('og_title', models.CharField(blank=True, max_length=60, verbose_name='Open-Graph-Titel')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='Open-Graph-Beschreibung')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Muss eine vollständige HTTPS-URL sein.', max_length=300, validators=[content.seo.validate_https_absolute_url], verbose_name='Kanonische URL')),
                ('noindex', models.BooleanField(default=False, verbose_name='Nicht indexieren')),
                ('navigation_label', models.CharField(blank=True, help_text='Optionaler kurzer Name für Navigation und Breadcrumbs.', max_length=120, verbose_name='Navigationsbezeichnung')),
                ('last_reviewed', models.DateField(blank=True, help_text='Für rechtliche Seiten das Datum der letzten inhaltlichen Prüfung.', null=True, verbose_name='Zuletzt geprüft am')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=160, verbose_name='Hero-Eyebrow')),
                ('hero_heading', models.CharField(max_length=240, verbose_name='Hero-Überschrift')),
                ('hero_text', wagtail.fields.RichTextField(blank=True, verbose_name='Hero-Text')),
                ('hero_ctas', wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('service_key', models.CharField(choices=[('eignungsdiagnostik', 'Eignungsdiagnostik'), ('internationale-rekrutierung', 'Internationale Rekrutierung'), ('volumen-projektbesetzung', 'Volumen- & Projektbesetzung'), ('employer-branding', 'Employer Branding')], max_length=80, unique=True, verbose_name='Service-Schlüssel')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Intro')),
                ('body_sections', wagtail.fields.StreamField([('section', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift', 'max_length': 240, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1), ('image', 2)]], {})})),
                ('cta_heading', models.CharField(blank=True, max_length=240, verbose_name='CTA-Überschrift')),
                ('cta_text', wagtail.fields.RichTextField(blank=True, verbose_name='CTA-Text')),
                ('cta', wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'internal', 'help_text': 'internal oder external', 'label': 'Linktyp', 'max_length': 8}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})})),
                ('show_calendly_cta', models.BooleanField(default=False, verbose_name='Calendly-CTA anzeigen')),
                ('hero_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero-Hintergrundbild')),
                ('hero_background_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Hero-Hintergrundvideo')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Open-Graph-Bild')),
            ],
            options={
                'verbose_name': 'Leistungsseite',
                'verbose_name_plural': 'Leistungsseiten',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
