# Generated by Django 5.2.17 on 2026-09-19 05:52

import content.seo
import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contactpage_cvpackagespage_legalpage_servicepage'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('og_title', models.CharField(blank=True, max_length=60, verbose_name='Open-Graph-Titel')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='Open-Graph-Beschreibung')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Muss eine vollständige HTTPS-URL sein.', max_length=300, validators=[content.seo.validate_https_absolute_url], verbose_name='Kanonische URL')),
                ('noindex', models.BooleanField(default=False, verbose_name='Nicht indexieren')),
                ('navigation_label', models.CharField(blank=True, help_text='Optionaler kurzer Name für Navigation und Breadcrumbs.', max_length=120, verbose_name='Navigationsbezeichnung')),
                ('last_reviewed', models.DateField(blank=True, help_text='Für rechtliche Seiten das Datum der letzten inhaltlichen Prüfung.', null=True, verbose_name='Zuletzt geprüft am')),
                ('source_key', models.CharField(max_length=160, unique=True, verbose_name='Quellschlüssel')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('open', 'Offen'), ('filled', 'Besetzt'), ('archived', 'Archiviert')], default='draft', max_length=20, verbose_name='Status')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='Veröffentlichungsdatum')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Schließungsdatum')),
                ('location_display', models.CharField(blank=True, max_length=200, verbose_name='Standortanzeige')),
                ('remote', models.BooleanField(default=False, verbose_name='Remote möglich')),
                ('category', models.CharField(blank=True, max_length=160, verbose_name='Kategorie')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Spezialisierung / Modul')),
                ('experience_display', models.CharField(blank=True, max_length=160, verbose_name='Erfahrung (Anzeige)')),
                ('employment_type', models.CharField(blank=True, max_length=160, verbose_name='Beschäftigungsart')),
                ('summary', wagtail.fields.RichTextField(blank=True, verbose_name='Einleitung / Zusammenfassung')),
                ('responsibilities', wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Aufgabe'})})),
                ('candidate_profile', wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Anforderung'})})),
                ('benefits', wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Vorteil'})})),
                ('application_email', models.EmailField(blank=True, max_length=254, verbose_name='Bewerbungs-E-Mail')),
                ('external_ats_identifier', models.CharField(blank=True, max_length=160, verbose_name='Externe ATS-ID')),
                ('external_ats_url', models.URLField(blank=True, verbose_name='Externe ATS-URL')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Open-Graph-Bild')),
            ],
            options={
                'verbose_name': 'Projektstelle',
                'verbose_name_plural': 'Projektstellen',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='JobsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('og_title', models.CharField(blank=True, max_length=60, verbose_name='Open-Graph-Titel')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='Open-Graph-Beschreibung')),
                ('canonical_url', models.URLField(blank=True, help_text='Optional. Muss eine vollständige HTTPS-URL sein.', max_length=300, validators=[content.seo.validate_https_absolute_url], verbose_name='Kanonische URL')),
                ('noindex', models.BooleanField(default=False, verbose_name='Nicht indexieren')),
                ('navigation_label', models.CharField(blank=True, help_text='Optionaler kurzer Name für Navigation und Breadcrumbs.', max_length=120, verbose_name='Navigationsbezeichnung')),
                ('last_reviewed', models.DateField(blank=True, help_text='Für rechtliche Seiten das Datum der letzten inhaltlichen Prüfung.', null=True, verbose_name='Zuletzt geprüft am')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=160, verbose_name='Hero-Eyebrow')),
                ('hero_heading', models.CharField(max_length=240, verbose_name='Hero-Überschrift')),
                ('hero_intro', wagtail.fields.RichTextField(blank=True, verbose_name='Hero-Intro')),
                ('search_label', models.CharField(blank=True, max_length=160, verbose_name='Suchfeld-Bezeichnung')),
                ('search_placeholder', models.CharField(blank=True, max_length=160, verbose_name='Suchfeld-Platzhalter')),
                ('filter_heading', models.CharField(blank=True, max_length=160, verbose_name='Filter-Überschrift')),
                ('location_filter_label', models.CharField(blank=True, max_length=120, verbose_name='Filter: Standort')),
                ('category_filter_label', models.CharField(blank=True, max_length=120, verbose_name='Filter: Kategorie')),
                ('remote_filter_label', models.CharField(blank=True, max_length=120, verbose_name='Filter: Remote')),
                ('empty_state_text', models.CharField(blank=True, max_length=240, verbose_name='Leerzustand')),
                ('result_count_format', models.CharField(blank=True, max_length=160, verbose_name='Ergebniszählung')),
                ('application_note', wagtail.fields.RichTextField(blank=True, verbose_name='Bewerbungshinweis')),
                ('default_application_email', models.EmailField(blank=True, max_length=254, verbose_name='Standard-Bewerbungs-E-Mail')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Open-Graph-Bild')),
            ],
            options={
                'verbose_name': 'Projektstellen-Übersicht',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
