# Generated by Django 5.2.17 on 2026-09-19 05:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_jobpage_jobsindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='contact_cta',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_ctas',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='candidatepage',
            name='closing_cta',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='candidatepage',
            name='hero_ctas',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='hero_ctas',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='cvpackagespage',
            name='hero_ctas',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='cvpackagespage',
            name='packages',
            field=wagtail.fields.StreamField([('package', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Paketname', 'max_length': 160}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Preis (Anzeige)', 'max_length': 120}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Erfahrungsbereich', 'max_length': 160, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Zielgruppe', 'max_length': 160, 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Beschreibung', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 7: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('label', 5), ('is_external', 6), ('page', 7), ('external_url', 8)]], {'label': 'CTA', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('name', 0), ('price_display', 1), ('experience_range', 2), ('audience', 3), ('description', 4), ('cta', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='employerpage',
            name='closing_cta',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='employerpage',
            name='hero_ctas',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='cta',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='hero_ctas',
            field=wagtail.fields.StreamField([('cta', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bezeichnung', 'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Interne Seite'), ('external', 'Externe URL')], 'label': 'Linktyp'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne Seite', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Externe URL', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_external', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
    ]
