# Generated by Django 5.2.17 on 2026-09-19 11:37

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_aboutpage_contact_cta_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerpage',
            name='closing_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Abschluss-Hintergrundbild'),
        ),
        migrations.AddField(
            model_name='employerpage',
            name='closing_copy',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Abschluss-Text'),
        ),
        migrations.AddField(
            model_name='employerpage',
            name='closing_eyebrow',
            field=models.CharField(blank=True, max_length=160, verbose_name='Abschluss-Eyebrow'),
        ),
        migrations.AddField(
            model_name='employerpage',
            name='closing_heading',
            field=models.CharField(blank=True, max_length=240, verbose_name='Abschluss-Überschrift'),
        ),
        migrations.AddField(
            model_name='employerpage',
            name='recruitment_region_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Regionen-Bild'),
        ),
        migrations.AddField(
            model_name='employerpage',
            name='services_eyebrow',
            field=models.CharField(blank=True, max_length=160, verbose_name='Leistungen-Eyebrow'),
        ),
        migrations.AddField(
            model_name='employerpage',
            name='services_heading',
            field=models.CharField(blank=True, max_length=240, verbose_name='Leistungen-Überschrift'),
        ),
        migrations.AddField(
            model_name='employerpage',
            name='why_eyebrow',
            field=models.CharField(blank=True, max_length=160, verbose_name='Warum-Kastell-Eyebrow'),
        ),
        migrations.AddField(
            model_name='employerpage',
            name='why_heading',
            field=models.CharField(blank=True, max_length=240, verbose_name='Warum-Kastell-Überschrift'),
        ),
    ]
