# Generated by Django 5.2.17 on 2026-09-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_employerpage_closing_background_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerpage',
            name='testimonials_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Kundenstimmen-Hintergrundbild'),
        ),
        migrations.AddField(
            model_name='employerpage',
            name='testimonials_eyebrow',
            field=models.CharField(blank=True, max_length=160, verbose_name='Kundenstimmen-Eyebrow'),
        ),
    ]
