# Generated by Django 5.2.17 on 2026-09-20 03:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_employerpage_testimonials_background_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepage',
            name='career_copy',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Karriere-Text'),
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='career_heading',
            field=models.CharField(blank=True, max_length=240, verbose_name='Karriere-Überschrift'),
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='career_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_career_pages', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='contact_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_contact_pages', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='contact_heading',
            field=models.CharField(blank=True, max_length=240, verbose_name='Kontakt-Überschrift'),
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='services_eyebrow',
            field=models.CharField(blank=True, max_length=160, verbose_name='Leistungen-Eyebrow'),
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='services_heading',
            field=models.CharField(blank=True, max_length=240, verbose_name='Leistungen-Überschrift'),
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='show_hero',
            field=models.BooleanField(default=False, help_text='Die Produktionsseite für Kandidat:innen beginnt direkt mit dem Leistungsbereich.', verbose_name='Hero anzeigen'),
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='testimonials_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_testimonial_pages', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='candidatepage',
            name='testimonials_eyebrow',
            field=models.CharField(blank=True, max_length=160, verbose_name='Kundenstimmen-Eyebrow'),
        ),
    ]
