# Generated by Django 5.2.17 on 2026-09-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_candidatepage_career_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepage',
            name='show_testimonial_content',
            field=models.BooleanField(default=False, help_text='Zeigt die Testimonial-Karten unter dem Kundenstimmen-Banner an.', verbose_name='Kundenstimmen anzeigen'),
        ),
        migrations.AddField(
            model_name='employerpage',
            name='show_testimonial_content',
            field=models.BooleanField(default=False, help_text='Zeigt die Testimonial-Karten unter dem Kundenstimmen-Banner an.', verbose_name='Kundenstimmen anzeigen'),
        ),
    ]
