# Generated by Django 5.2.17 on 2026-09-20 06:16

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_candidatepage_show_testimonial_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='team_eyebrow',
            field=models.CharField(blank=True, max_length=160, verbose_name='Team-Eyebrow'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_heading',
            field=models.CharField(blank=True, max_length=240, verbose_name='Team-Überschrift'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_lead',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Team-Einleitung'),
        ),
    ]
